# Konfigurasi tambahan untuk environment lokal (development)
services:
  traefik:
    labels:
      - "traefik.enable=true"  # Aktifkan routing untuk container ini

      # Dashboard lokal via HTTP
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web"  # Gunakan HTTP (port 80)
      - "traefik.http.routers.traefik.service=api@internal"  # Dashboard bawaan Traefik
