# File untuk konfigurasi saat pengembangan (lokal)
version: "3.8"

services:
  traefik:
    labels:
      - "traefik.enable=true"

      # Router untuk dashboard di lokal (traefik.localhost)
      - "traefik.http.routers.traefik-localhost.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik-localhost.entrypoints=web"
      - "traefik.http.routers.traefik-localhost.service=api@internal"

volumes:
  traefik_acme:      
