# File konfigurasi statis Traefik (dibaca saat startup)

api:
  dashboard: true       # Aktifkan dashboard Traefik
  insecure: true        # Hanya untuk lokal (HTTP tanpa auth), boleh karena tidak expose ke publik

entryPoints:
  web:
    address: ":80"       # HTTP
  websecure:
    address: ":443"      # HTTPS

providers:
  docker:
    exposedByDefault: false  # Hanya container yang beri label "traefik.enable=true" yang didaftarkan

  file:
    filename: /etc/traefik/conf/usersfile  # Digunakan untuk auth basic di production (dashboard)
