# File konfigurasi statis Traefik (dibaca saat startup)

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false  # Hanya container dengan label traefik.enable=true

certificatesResolvers:
  letsencrypt:
    acme:
      email: odoo@simetri-sinergi.id
      storage: /acme.json
      httpChallenge:
        entryPoint: web  # Let's Encrypt akan verifikasi via HTTP di port 80

api:
  dashboard: true     # Aktifkan dashboard
  insecure: false     # Nonaktifkan akses tanpa router

log:
  level: DEBUG         # Untuk debugging konfigurasi
