# Konfigurasi statis utama Traefik

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

api:
  dashboard: true  # Aktifkan dashboard internal

providers:
  docker:
    exposedByDefault: false  # Hanya container dengan traefik.enable=true yang dilayani

certificatesResolvers:
  letsencrypt:
    acme:
      email: odoo@simetri-sinergi.id
      storage: /acme.json  # Lokasi tempat sertifikat disimpan (pakai volume internal)
      tlsChallenge: true
